---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gickup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gickup.labels" . | nindent 4 }}
data:
  conf.yml: |
    source:
      gitea:
        - token_file: /etc/gickup/secrets/forgejo-token
          user: nikmosi
          url: https://git.xinfra.ru
          ssh: true
          sshkey: /tmp/gickup-ssh-key
    destination:
      gitea:
        - token_file: /etc/gickup/secrets/codeberg-token
          user: nikmosi
          url: https://codeberg.org
          mirror:
            enabled: true
          visibility:
            repositories: private
