---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gickup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gickup.labels" . | nindent 4 }}
data:
  conf.yml: |
    {{- toYaml .Values.config | nindent 4 }}
