apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zipline.fullname" . }}
  labels:
    {{- include "zipline.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zipline.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zipline
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "zipline.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zipline.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: TZ
              value: "Asia/Novosibirsk"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "zipline.secretName" . }}
                  key: {{ .Values.postgresql.auth.passwordKey }}
          command:
            - sh
            - -c
            - >
              until pg_isready -h {{ include "zipline.postgresqlServiceName" . }} -p 5432 -U {{ .Values.postgresql.auth.username }} -d {{ .Values.postgresql.auth.database }};
              do echo waiting for postgresql; sleep 2; done
      containers:
        - name: zipline
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "zipline.secretName" . }}
                  key: {{ .Values.postgresql.auth.passwordKey }}
            - name: POSTGRESQL_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRESQL_HOST
              value: {{ include "zipline.postgresqlServiceName" . | quote }}
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres://$(POSTGRESQL_USER):$(POSTGRESQL_PASSWORD)@$(POSTGRESQL_HOST):$(POSTGRESQL_PORT)/$(POSTGRESQL_DB)"
            - name: CORE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "zipline.secretName" . }}
                  key: {{ .Values.secrets.coreSecretKey }}
            {{- range $name, $value := .Values.zipline.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.zipline.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.uploads.enabled }}
            - name: uploads
              mountPath: /zipline/uploads
            {{- end }}
            {{- if .Values.persistence.public.enabled }}
            - name: public
              mountPath: /zipline/public
            {{- end }}
            {{- if .Values.persistence.themes.enabled }}
            - name: themes
              mountPath: /zipline/themes
            {{- end }}
      volumes:
        {{- if .Values.persistence.uploads.enabled }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ include "zipline.uploadsPvcName" . }}
        {{- end }}
        {{- if .Values.persistence.public.enabled }}
        - name: public
          persistentVolumeClaim:
            claimName: {{ include "zipline.publicPvcName" . }}
        {{- end }}
        {{- if .Values.persistence.themes.enabled }}
        - name: themes
          persistentVolumeClaim:
            claimName: {{ include "zipline.themesPvcName" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
