apiVersion: v1
kind: Service
metadata:
  name: {{ include "zipline.postgresqlServiceName" . }}
  labels:
    {{- include "zipline.postgresqlLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "zipline.postgresqlSelectorLabels" . | nindent 4 }}
