apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zipline.postgresqlServiceName" . }}
  labels:
    {{- include "zipline.postgresqlLabels" . | nindent 4 }}
spec:
  serviceName: {{ include "zipline.postgresqlServiceName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "zipline.postgresqlSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "zipline.postgresqlLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "zipline.secretName" . }}
                  key: {{ .Values.postgresql.auth.passwordKey }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: TZ
              value: "Asia/Novosibirsk"
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          {{- if .Values.persistence.postgresql.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "zipline.postgresqlPvcName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
