{{- if not .Values.secrets.existingSecret }}
{{- $secretName := include "zipline.secretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $existingData := default dict $existing.data }}
{{- $passwordKey := .Values.postgresql.auth.passwordKey }}
{{- $coreSecretKey := .Values.secrets.coreSecretKey }}
{{- $postgresPassword := randAlphaNum 32 }}
{{- if hasKey $existingData $passwordKey }}
{{- $postgresPassword = (index $existingData $passwordKey | b64dec) }}
{{- end }}
{{- $coreSecret := randAlphaNum 32 }}
{{- if hasKey $existingData $coreSecretKey }}
{{- $coreSecret = (index $existingData $coreSecretKey | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "zipline.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $passwordKey }}: {{ $postgresPassword | quote }}
  {{ $coreSecretKey }}: {{ $coreSecret | quote }}
{{- end }}
