---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-credentials
  namespace: apps-zot
stringData:
  oidc-credentials.json: |
    {
      "clientid": "PKNtTDqi5REDQYuUiIMScLAtQNnCeDTMglxhU04I",
      "clientsecret": "KJbBsSUJzpXZX6EZQAtIPD8GrkunSJMuG8J6wRZdWONhGaPHHEfRBQmIxO6MNFpS44dlgKFQ4nWVU78kDQRT6M34rL3gpBbqb4cibFD8AhwoxLouYjqZPl1mawfzy2Cy"
    }
