---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-xinfra-ru
spec:
  secretName: wildcard-xinfra-ru-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "xinfra.ru"
    - "*.xinfra.ru"
