---
authentik:
  secret_key: "x8gN3vlObrSzpzPEgvGlDkhgMMksyDsaZqoCQeveyOspSTkuuGcUEMu0Hwah7HOHMjmNubn/6H2E/nT7"
  error_reporting:
    enabled: false
  postgresql:
    password: "jS2b+4dOzSI,M$>}vE/XN0!Z|#v>W\\T'"

global:
  env:
    - name: TZ
      value: Asia/Novosibirsk

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 3s
  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - authentik.xinfra.ru
    tls:
      - hosts:
          - authentik.xinfra.ru
        secretName: wildcard-xinfra-ru-tls

postgresql:
  enabled: true
  auth:
    password: "jS2b+4dOzSI,M$>}vE/XN0!Z|#v>W\\T'"
  primary:
    extraEnvVars:
      - name: POSTGRES_DB
        value: '{{ (include "postgresql.v1.database" .) }}'
      - name: TZ
        value: Asia/Novosibirsk

worker:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 3s
