---
authentik:
  existingSecret:
    secretName: authentik-config
  error_reporting:
    enabled: false
  postgresql:
    host: "{{ .Release.Name }}-postgresql"
    name: authentik
    user: authentik

global:
  env:
    - name: TZ
      value: Asia/Novosibirsk

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 60s
      scrapeTimeout: 3s
  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - authentik.xinfra.ru
    tls:
      - hosts:
          - authentik.xinfra.ru
        secretName: wildcard-xinfra-ru-tls

postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-postgresql
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    extraEnvVars:
      - name: POSTGRES_DB
        value: '{{ (include "postgresql.v1.database" .) }}'
      - name: TZ
        value: Asia/Novosibirsk

worker:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 60s
      scrapeTimeout: 3s
