---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ui.name | quote }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ui.type }}
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ui.port }}
      targetPort: {{ .Values.service.ui.targetPort }}
      protocol: TCP
