---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-valkey
  namespace: apps-forgejo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: forgejo-valkey
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-valkey
  namespace: apps-forgejo
spec:
  serviceName: forgejo-valkey
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo-valkey
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forgejo-valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8-alpine
          imagePullPolicy: IfNotPresent
          command:
            - valkey-server
          args:
            - --appendonly
            - "yes"
            - --save
            - "60"
            - "1000"
            - --dir
            - /data
          env:
            - name: TZ
              value: "Asia/Novosibirsk"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
