---
apiVersion: v2
name: gickup
description: A Helm chart for gickup - mirror Git repositories between hosts
type: application
version: 0.1.2
appVersion: "0.10.45"
keywords:
  - git
  - backup
  - mirror
home: https://github.com/cooperspencer/gickup
sources:
  - https://github.com/cooperspencer/gickup
