---
schedule: "0 2 * * *"
backoffLimit: 2
activeDeadlineSeconds: 7200

config:
  source:
    gitea:
      - token_file: /etc/gickup/secrets/forgejo-token
        user: nikmosi
        url: https://git.xinfra.ru
        ssh: true
        sshkey: /tmp/gickup-ssh-key
  destination:
    gitea:
      - token_file: /etc/gickup/secrets/codeberg-token
        user: nikmosi
        url: https://codeberg.org
        mirror:
          enabled: true
        visibility:
          repositories: private

image:
  repository: buddyspencer/gickup
  pullPolicy: IfNotPresent
  tag: "0.10.45"

initImage:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "1.37.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

existingSecret: gickup-secrets

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

initResources:
  requests:
    cpu: 15m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
