---
image:
  registry: registry.gitlab.com
  image: gitlab-org/gitlab-runner

imagePullSecrets: []

livenessProbe: {}
#   initialDelaySeconds: 60
#   periodSeconds: 60
#   successThreshold: 1
#   failureThreshold: 3
#   terminationGracePeriodSeconds: 30

## Configure the readinessProbe
readinessProbe: {}
#   initialDelaySeconds: 60
#   periodSeconds: 60
#   successThreshold: 1
#   failureThreshold: 3

gitlabUrl: https://gitlab.your-domain.com/
unregisterRunners: true
terminationGracePeriodSeconds: 3600
concurrent: 5
checkInterval: 3

metrics:
  enabled: true
  podMonitor:
    enabled: true
    interval: 30s
    path: /metrics

rbac:
  create: true
  generatedServiceAccountName: "gitlab-runner"
  rules: []
    # - resources: ["events"]
    #   verbs: ["list", "watch"]
    # - resources: ["namespaces"]
    #   verbs: ["create", "delete"]
    # - resources: ["pods"]
    #   verbs: ["create","delete","get"]
    # - apiGroups: [""]
    #   resources: ["pods/attach","pods/exec"]
    #   verbs: ["get","create","patch","delete"]
    # - apiGroups: [""]
    #   resources: ["pods/log"]
    #   verbs: ["get","list"]
    # - resources: ["secrets"]
    #   verbs: ["create","delete","get","update"]
    # - resources: ["serviceaccounts"]
    #   verbs: ["get"]
    # - resources: ["services"]
    #   verbs: ["create","get"]

serviceAccount:
  create: true
  name: "gitlab-runner"
  # TODO: set

runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{ default .Release.Namespace .Values.runners.jobNamespace }}"
        service_account = "gitlab-runner"
        image = "alpine"

        cpu_request = "500m"
        cpu_limit = "1000m"
        memory_request = "1Gi"
        memory_limit = "2Gi"
        helper_cpu_request = "100m"
        helper_cpu_limit = "250m"
        helper_memory_request = "128Mi"
        helper_memory_limit = "256Mi"
        service_cpu_request = "250m"
        service_cpu_limit = "500m"
        service_memory_request = "256Mi"
        service_memory_limit = "512Mi"

        image_pull_secrets = ["zot"]

        [[runners.kubernetes.volumes.secret]]
          name = "zot"
          mount_path = "/kaniko/.docker"
          read_only = true

          [runners.kubernetes.volumes.secret.items]
            ".dockerconfigjson" = "config.json"

  secret: gitlab-runner-secret

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

resources:
  limits:
    memory: 4Gi
    cpu: 2000m
    ephemeral-storage: 512Mi
  requests:
    memory: 128Mi
    cpu: 100m
    ephemeral-storage: 256Mi

secrets: []
  # Example:
  # - name: my-secret
  # - name: myOtherSecret
  #   items:
  #     - key: key_one
  #       path: path_one

configMaps: {}

## Additional volumeMounts to add to the runner container
##
volumeMounts: []
  # Example:
  # - name: my-volume
  #   mountPath: /mount/path

## Additional volumes to add to the runner deployment
##
volumes: []
  # Example:
  # - name: my-volume
  #   persistentVolumeClaim:
  #     claimName: my-pvc
