---
apiVersion: v2
name: adguard
description: A Helm chart for AdGuard Home DNS server
type: application
version: 0.1.2
appVersion: "v0.107.76"
keywords:
  - dns
  - adblock
  - adguard
home: https://adguard.com/en/adguard-home/overview.html
sources:
  - https://github.com/AdguardTeam/AdGuardHome
