{{- if and .Values.secret.jwtSecret .Values.secret.databaseUrl (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supersync.fullname" . }}
  labels:
    {{- include "supersync.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  {{- with .Values.secret.smtpUser }}
  SMTP_USER: {{ . | quote }}
  {{- end }}
  {{- with .Values.secret.smtpPass }}
  SMTP_PASS: {{ . | quote }}
  {{- end }}
{{- end }}
