{{- if .Values.rabbitmq.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twitch-sub-check.rabbitmqFullname" . }}
  labels:
    {{- include "twitch-sub-check.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.port }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "twitch-sub-check.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }}
