{{- if and .Values.rabbitmq.enabled (not .Values.rabbitmq.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twitch-sub-check.rabbitmqSecretName" . }}
  labels:
    {{- include "twitch-sub-check.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
stringData:
  {{ .Values.rabbitmq.auth.secretKeys.username }}: {{ .Values.rabbitmq.auth.username | quote }}
  {{ .Values.rabbitmq.auth.secretKeys.password }}: {{ .Values.rabbitmq.auth.password | quote }}
{{- end }}
