{{- if not .Values.credentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twitch-sub-check.credentialsSecretName" . }}
  labels:
    {{- include "twitch-sub-check.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.secretKeys.twitchClientId }}: {{ .Values.credentials.values.twitchClientId | quote }}
  {{ .Values.credentials.secretKeys.twitchClientSecret }}: {{ .Values.credentials.values.twitchClientSecret | quote }}
  {{ .Values.credentials.secretKeys.telegramBotToken }}: {{ .Values.credentials.values.telegramBotToken | quote }}
  {{ .Values.credentials.secretKeys.telegramChatId }}: {{ .Values.credentials.values.telegramChatId | quote }}
{{- end }}
