---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dozzle-data
  namespace: monitoring
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
