replicaCount: 1

namespaceOverride: reflector

configuration:
  logging:
    minimumLevel: Information

rbac:
  enabled: true

serviceAccount:
  create: true

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
