apiVersion: v2
name: twitch-sub-check
description: Deploy twitch-sub-bot on Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.25.0-0"
maintainers:
  - name: codex-box
sources:
  - https://git.xinfra.ru/nikmosi/twitch-sub-bot
