---
apiVersion: v2
name: traffic-noise
description: Deploy the Locust traffic-noise workload
type: application
version: 0.1.1
appVersion: "2.44.0"
keywords:
  - locust
  - load-testing
  - traffic
dependencies:
  - name: locust
    version: "0.31.6"
    repository: "https://charts.deliveryhero.io/"
