---
loadtest:
  name: stealth-noise
  locust_host: "https://google.com"
  headless: true

  locust_locustfile_configmap: "stealth-locustfile"
  locust_locustfile: "main.py"
  locust_lib_configmap: ""

master:
  replicas: 1
  args:
    - --users=10
    - --spawn-rate=1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

worker:
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
