---
apiVersion: v2
name: supersync
description: Helm chart for SuperSync server - high-performance synchronization server for Super Productivity
type: application
version: 0.1.4
appVersion: "0d2538-26-01-25"
kubeVersion: ">=1.27.0-0"
keywords:
  - sync
  - super-productivity
  - supersync
home: https://super-productivity.com
sources:
  - https://github.com/super-productivity/super-productivity/tree/master/packages/super-sync-server
dependencies:
  - name: postgresql
    version: ~18.7.x
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
