{{- if and (not .Values.xray.existingConfigMap) (not .Values.xray.existingSecret) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xray.fullname" . }}
  labels:
    {{- include "xray.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- .Values.xray.config | nindent 4 }}
{{- end }}
