---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: apps-ntfy
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: https://ntfy.xinfra.ru
