---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-ingress
  namespace: apps-ntfy
spec:
  tls:
    - hosts:
        - dozzle.xinfra.ru
      secretName: wildcard-xinfra-ru-tls

  rules:
    - host: ntft.xinfra.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy-svc
                port:
                  number: 80
