---
vikunja:
  configMaps:
    config:
      enabled: true
      data:
        config.yml: |
          service:
            publicurl: https://vikunja.xinfra.ru
            enableregistration: false
          auth:
            local:
                enabled: true
            openid:
                enabled: true
                providers:
                    authentik:
                        name: "authentik Login"
                        usernamefallback: true
                        emailfallback: true
                        authurl: https://authentik.xinfra.ru/application/o/vikunja/
                        clientid: 9GaHg9eweQN8edJ1J4Ox205V5EkktTM907jGjzrb
                        clientsecret: 4Hp28B8Xc4NPRRFQcbHwby9rRjUZLBIxMDtW08qRJA3Zcs8q0pU0Nvgi4CWgO57Isv6UyAKytwaVhO6DUVTjnvkJG9Kz3dDXsS2v8t7zz9D86JAFLsKpx7ECZU8yxnFe
                        scope: openid email profile
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 256Mi
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      mountPath: /app/vikunja/files
  ingress:
    main:
      enabled: true
      hosts:
        - host: vikunja.xinfra.ru
          paths:
            - path: /
      tls:
        - hosts:
            - vikunja.xinfra.ru
          secretName: wildcard-xinfra-ru-tls
